### ISSUE TITLE
Error installing on Linux (Ubuntu 16.04) on Windows 10

### ISSUE THREAD

**Issue by ashishchandr70** [holochain/holochain-proto#771] opened 2018-09-11 15:16 UTC
Hi,

I got the following error while installing on Ubuntu 16.04. Not sure what to make of it except that something is being invoked and is not available. I tried searching for this issue here but couldn't find another instance of it.

Ubuntu info:

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"

[...]
go get ./cmd/bs/
github.com/holochain/holochain-proto/cmd/bs
gx/ipfs/QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ/go-crypto/blake2b.supportAVX2: relocation target runtime.support_avx2 not defined
Makefile:43: recipe for target 'all' failed
make: *** [all] Error 2

A complete log of the make command is provided below.

$ make
gx-go get github.com/holochain/holochain-proto
[done] [fetch]   44ms  QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL go-libp2p
[done] [fetch]   24ms  QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa go-semver
[done] [fetch]   11ms  QmSU6eubNdhXjFBJBSksTp8kv8YRub8mGAPv8tVJHmL2EU go-ipfs-util
[done] [fetch]   15ms  QmWSvDKkcno2UyDg13rUBwWfhRsdj7uR3daAq57VoG5QeN mdns
[done] [fetch]   3ms   QmWHgLqrghM9zw77nF6gdvT9ExQ2RB9pLxkd8sDHZf1rWb go-temp-err-catcher
[done] [fetch]   1ms   QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL go-msgio
[done] [fetch]   2ms   QmUusaX99BZoELh7dmPgirqRQ1FAmMnmnBn3oiqDFGBUSc go-keyspace
[done] [fetch]   24ms  QmXY77cVe7rVRQXZZQRioukUM7aRW3BTcAgJe12MCtb3Ji go-multiaddr
[done] [fetch]   1ms   QmTnsezaB1wWNRHeHnYrm8K4d5i9wtyj3GsqjC3Rt5b5v5 go-multistream
[done] [fetch]   1ms   QmT8rehPR3F6bmwL6zjUN8XpiDBFFpMP2myPdC6ApsWfJf go-base58
[done] [fetch]   2ms   QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ go-crypto
[done] [fetch]   1ms   QmQHGMVmrsgmqUG8ih3puNXUJneSpi13dkcZpzLKkskUkH go-detect-race
[done] [fetch]   36ms  QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP goprocess
[done] [fetch]   1ms   QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 go-log
[done] [fetch]   34ms  QmX3U3YXCQ6UYBxq2LVWF8dARS1hPUTEYLrSx654Qyxyw6 go-multiaddr-net
[done] [fetch]   5ms   QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV gogo-protobuf
[done] [fetch]   7ms   QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB go-metrics
[done] [fetch]   21ms  QmeQW4ayVqi7Jjay1SrP2wYydsH9KwSrzQBnqyC25gPFnG go-notifier
[done] [fetch]   32ms  QmU9a9NV9RdPNwZQDYd5uKsm6N6LJLSvLbywDDYFbaaC6P go-multihash
[get ] [fetch]         QmT4PgCNdv73hnFAqzHqwW44q7M9PWpykSswHDxndquZbc go-libp2p-loggables
[get ] [fetch]         QmfQAY7YU4fQi3sjGLs1hwkM2Aq7dxgDyoMjaKN4WBWvcB go-libp2p-interface-conn
[done] [fetch]   85ms  QmT4PgCNdv73hnFAqzHqwW44q7M9PWpykSswHDxndquZbc go-libp2p-loggables
[done] [fetch]   25ms  QmYvsG72GsfLgUeSojXArjnU6L4Wmwk7wuAxtNLuyXcc1T randbo
[done] [fetch]   18ms  QmZNkThpqfVXs9GNbexPrfBbXSLNYeKrE7jwFM2oqHbyqN go-libp2p-protocol
[done] [fetch]   31ms  QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M go-libp2p-secio
[done] [fetch]   88ms  QmPgDWmTmuzvP7QE5zwo1TmjbJme9pmZHNujB2453jkCTr go-libp2p-peerstore
[done] [fetch]   75ms  QmQVm7pWYKPStMeMrXNRpvAJE5rSm9ThtQoNmjNHC7sh3k go-libp2p-transport
[done] [fetch]   74ms  QmbrUTiVDSK3WGePN18qVjpGYmvXQt6YVPyyGoXWx593uq go-tcp-transport
[done] [fetch]   110ms QmQBB2dQLmQHJgs2gqZ3iqL2XiuCtUCvXzWt5kMXDf5Zcr go-maddr-filter
[done] [fetch]   69ms  QmXZYkfBN1cABhBZRaEwLzgEB5B3nAGiJYCmhWbDW3cDus go-peerstream
[done] [fetch]   210ms QmfQAY7YU4fQi3sjGLs1hwkM2Aq7dxgDyoMjaKN4WBWvcB go-libp2p-interface-conn
[done] [fetch]   69ms  QmZQa5J7j7kd44GGC4aKX8J9JGGzCMqwGzcEFqGV1YD57A mafmt
[done] [fetch]   13ms  QmTd4Jgb4nbJq5uR55KJgGLyHWmM3dovS21D1HcwRneSLu gorocheck
[done] [fetch]   15ms  QmVJGsPeK3vwtEyyTxpCs47yjBYMmYsAhEouPDF3Gb2eK3 go-addr-util
[done] [fetch]   17ms  QmNa31VPzC561NWwRsJLE7nGYZYuuD2QfpK2b1q9BK54J1 go-libp2p-net
[done] [fetch]   15ms  QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i go-libp2p-conn
[done] [fetch]   143ms QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14 go-libp2p-metrics
[done] [fetch]   39ms  QmQkeGXc9ZuQ5upVFpd2EjKvgw9aVh1BbtAgvNGVcebmmX go-libp2p-blankhost
[done] [fetch]   121ms QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh go-libp2p-swarm
[done] [fetch]   38ms  Qmc1XhrFEiSeBNn3mpfg6gEuYCt5im2gYmNVmncsvmpeAk go-libp2p-host
[done] [fetch]   37ms  QmeXm9iwA4cURNmexpuBucDWcV38jNHdqpGcb7yoyP6e4G go-libp2p-nat
[done] [fetch]   51ms  QmQGX417WoxKxDJeHqouMEmmH4G1RCENNSzkZYHrXy3Xb3 go-libp2p-netutil
[done] [fetch]   10ms  QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB go-libp2p-peer
[done] [fetch]   27ms  QmNWCEvi7bPRcvqAV8AKLGVNoQdArWi7NJayka2SM4XtRe go-smux-yamux
[done] [fetch]   91ms  QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo go-libp2p-crypto
[done] [fetch]   1ms   QmQvJiADDe7JR4m968MwXobTCCzUqQkP87aRHe29MEBGHV go-logging
[done] [fetch]   10ms  QmS7xUmsTdVNU2t1bPV6o9aXuXfufAjNGYgh2bcN2z9DAs go-multiaddr-dns
[done] [fetch]   89ms  Qmf7GSJ4omRJsvA9uzTqzbnVhq4RWLPzjzW4xJzUta4dKE go-libp2p-circuit
[done] [fetch]   152ms QmVniQJkdzLZaZwzwMdd3dJTvWiJ1DQEkreVy6hs6h7Vk5 go-smux-multistream
[done] [fetch]   2ms   QmYNGtJHgaGZkpzq8yG6Wxqm6EQTKqgpBfnyyGBKbZeDUi go-randbuf
[done] [fetch]   108ms QmYkCrTwivapqdB3JbwvwvxymseahVkcm46ThRMAA24zCr go-libp2p-interface-connmgr
[done] [fetch]   1ms   QmWchsfMt9Re1CQaiHqPQC1DrZ9bkpa6n229dRYkGyLXNh dns
[done] [fetch]   2ms   QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC go-net
[done] [fetch]   1ms   QmQPWTeQJnJE7MYu6dJTiNTQRNuqBr41dis6UgY6Uekmgd keccakpg
[done] [fetch]   1ms   QmfJHywXQu98UeZtGJBQrPAR6AtmDjjbe3qjTo9piXHPnx murmur3
[done] [fetch]   122ms QmNp85zy9RLrQ5oQD4hPyS39ezrrXpcaa7R4Y9kxdWQLLQ go-cid
[done] [fetch]   12ms  QmNhVCV7kgAqW6oh6n8m9myxT2ksGPhVZnHkzkBvR5qg2d go-multicodec-packed
[done] [fetch]   14ms  QmdicniYXy49AFCSVTZeYmo997kT5XJRzZLokzJCrywR2U go-ws-transport
[done] [fetch]   13ms  QmY9JXR3FupnYAYJWK9aMr9bCpqWKcToQ1tz8DVGTrHpHw go-stream-muxer
[done] [fetch]   29ms  QmQq9YzmdFdWNTDdArueGyD7L5yyiRQigrRHJnTGkxcEjT go-libp2p-interface-pnet
[done] [fetch]   4ms   QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts websocket
[done] [fetch]   4ms   Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ go-text
[done] [fetch]   3ms   QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u yamux
[done] [fetch]   27ms  QmQ8t8yZJv6bTgnDcHMPMgpUcSTnpNMGPjFxmGwZ2MWak9 go-nat
[done] [fetch]   12ms  QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV go.uuid
[done] [fetch]   173ms QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo go-reuseport
[done] [fetch]   2ms   QmYsYNh6saxUYHajdj49uiRzdxQgiFTtymrjf3d1f2Cer4 go-nat-pmp
[done] [fetch]   152ms QmQtBcHtRy9BxjawZjWJBn8aSKbqraBnQiVsc3wt9w9TTn goupnp
[done] [fetch]   2ms   Qmf2fBLzCvFxs3vvZaoQyKSTv2rjApek4F1kzRxAfK6P4P gateway
[done] [fetch]   3ms   QmWq5PJgAQKDWQerAijYUVKW8mN5MDatK5j7VMp8rizKQd btcec
[done] [fetch]   1ms   QmQ51pHe6u7CWodkUGDLqaCEMchkbMt7VEZnECF5mp6tVb ed25519
[done] [fetch]   127ms QmQFhPsJCp82az4SXbziP9QcVSqggEELnV9wGZqMR1EfMB go-smux-spdystream
[done] [fetch]   100ms QmafgXF3u3QSWErQoZ2URmQp5PFG384htoE7J338nS2H7T go-multibase
[done] [fetch]   2ms   QmSGRM5Udmy1jsFBr1Cawez7Lt7LZ3ZKA23GGVEsiEW6F3 eventfd
[done] [fetch]   2ms   QmcLqWSFsaQ8Ujh8Ys8i9JPHVy1CcdPoqV23M9S3ufdVbn go-sockaddr
[done] [fetch]   2ms   Qma73Sqt13DzHzveZ667BBfraM7MuMrPepUXjmv812JhRS go-net-resolve-addr
[done] [fetch]   2ms   QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw GoEndian
[done] [fetch]   2ms   QmWjNfGgm61ABELTxPDwvNDm18j1EmQiPt9zXkCSEYgMDm spdystream
[done] [fetch]   1ms   QmfVj3x4D6Jkq9SEoi5n2NmoUomLwoeiwnYz2KQa15wRw6 base32
[done] [install] 1ms   QmefgzMbKZYsmHFkLqxgaTBG9ypeEjrdWRD5WXH4j1cWDL go-libp2p
[done] [install] 1ms   QmcrrEpx3VMUbrbgVroH3YiYyUS5c4YAykzyPJWKspUYLa go-semver
[done] [install] 1ms   QmWSvDKkcno2UyDg13rUBwWfhRsdj7uR3daAq57VoG5QeN mdns
[done] [install] 1ms   QmRQhVisS8dmPbjBUthVkenn81pBxrx1GxE281csJhm2vL go-msgio
[done] [install] 2ms   QmSU6eubNdhXjFBJBSksTp8kv8YRub8mGAPv8tVJHmL2EU go-ipfs-util
[done] [install] 1ms   QmUusaX99BZoELh7dmPgirqRQ1FAmMnmnBn3oiqDFGBUSc go-keyspace
[done] [install] 1ms   QmTnsezaB1wWNRHeHnYrm8K4d5i9wtyj3GsqjC3Rt5b5v5 go-multistream
[done] [install] 1ms   QmQHGMVmrsgmqUG8ih3puNXUJneSpi13dkcZpzLKkskUkH go-detect-race
[done] [install] 0s    QmSF8fPo3jgVBAy8fpdjjYqgG87dkJgUprRBHRd2tmfgpP goprocess
[done] [install] 2ms   QmSpJByNKFX1sCsHBEp3R73FL4NF6FnQTEGyNAXHm2GS52 go-log
[done] [install] 1ms   QmX3U3YXCQ6UYBxq2LVWF8dARS1hPUTEYLrSx654Qyxyw6 go-multiaddr-net
[done] [install] 0s    QmU9a9NV9RdPNwZQDYd5uKsm6N6LJLSvLbywDDYFbaaC6P go-multihash
[done] [install] 1ms   QmSMZwvs3n4GBikZ7hKzT17c3bk65FmyZo2JqtJ16swqCv multiaddr-filter
[done] [install] 1ms   QmT8rehPR3F6bmwL6zjUN8XpiDBFFpMP2myPdC6ApsWfJf go-base58
[done] [install] 4ms   QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ go-crypto
[done] [install] 1ms   QmZ4Qi3GaRbjcx28Sme5eMH7RQjGkt8wHxt2a65oLaeFEV gogo-protobuf
[done] [install] 0s    QmXY77cVe7rVRQXZZQRioukUM7aRW3BTcAgJe12MCtb3Ji go-multiaddr
[done] [install] 1ms   QmeYJHEk8UjVVZ4XCRTZe6dFQrb8pGWD81LYCgeLp8CvMB go-metrics
[done] [install] 0s    QmYvsG72GsfLgUeSojXArjnU6L4Wmwk7wuAxtNLuyXcc1T randbo
[done] [install] 2ms   QmeQW4ayVqi7Jjay1SrP2wYydsH9KwSrzQBnqyC25gPFnG go-notifier
[done] [install] 1ms   QmWHgLqrghM9zw77nF6gdvT9ExQ2RB9pLxkd8sDHZf1rWb go-temp-err-catcher
[done] [install] 1ms   QmXZYkfBN1cABhBZRaEwLzgEB5B3nAGiJYCmhWbDW3cDus go-peerstream
[done] [install] 1ms   QmZQa5J7j7kd44GGC4aKX8J9JGGzCMqwGzcEFqGV1YD57A mafmt
[done] [install] 0s    QmTd4Jgb4nbJq5uR55KJgGLyHWmM3dovS21D1HcwRneSLu gorocheck
[done] [install] 5ms   QmT4PgCNdv73hnFAqzHqwW44q7M9PWpykSswHDxndquZbc go-libp2p-loggables
[done] [install] 1ms   QmZfwmhbcgSDGqGaoMMYx8jxBGauZw75zPjnZAyfwPso7M go-libp2p-secio
[done] [install] 1ms   QmPgDWmTmuzvP7QE5zwo1TmjbJme9pmZHNujB2453jkCTr go-libp2p-peerstore
[done] [install] 0s    QmQVm7pWYKPStMeMrXNRpvAJE5rSm9ThtQoNmjNHC7sh3k go-libp2p-transport
[done] [install] 3ms   QmbrUTiVDSK3WGePN18qVjpGYmvXQt6YVPyyGoXWx593uq go-tcp-transport
[done] [install] 1ms   QmQBB2dQLmQHJgs2gqZ3iqL2XiuCtUCvXzWt5kMXDf5Zcr go-maddr-filter
[done] [install] 1ms   QmZNkThpqfVXs9GNbexPrfBbXSLNYeKrE7jwFM2oqHbyqN go-libp2p-protocol
[done] [install] 1ms   QmVJGsPeK3vwtEyyTxpCs47yjBYMmYsAhEouPDF3Gb2eK3 go-addr-util
[done] [install] 1ms   QmWRCn8vruNAzHx8i6SAXinuheRitKEGu8c7m26stKvsYx go-testutil
[done] [install] 4ms   QmTi4629yyHJ8qW9sXFjvxJpYcN499tHhERLZYdUqwRU9i go-libp2p-conn
[done] [install] 3ms   QmNa31VPzC561NWwRsJLE7nGYZYuuD2QfpK2b1q9BK54J1 go-libp2p-net
[done] [install] 1ms   QmQbh3Rb7KM37As3vkHYnEFnzkVXNCP8EYGtHz6g2fXk14 go-libp2p-metrics
[done] [install] 1ms   QmfQAY7YU4fQi3sjGLs1hwkM2Aq7dxgDyoMjaKN4WBWvcB go-libp2p-interface-conn
[done] [install] 0s    Qmc1XhrFEiSeBNn3mpfg6gEuYCt5im2gYmNVmncsvmpeAk go-libp2p-host
[done] [install] 0s    QmdQFrFnPrKRQtpeHKjZ3cVNwxmGKKS2TvhJTuN9C9yduh go-libp2p-swarm
[done] [install] 1ms   QmeXm9iwA4cURNmexpuBucDWcV38jNHdqpGcb7yoyP6e4G go-libp2p-nat
[done] [install] 2ms   QmQGX417WoxKxDJeHqouMEmmH4G1RCENNSzkZYHrXy3Xb3 go-libp2p-netutil
[done] [install] 1ms   QmQkeGXc9ZuQ5upVFpd2EjKvgw9aVh1BbtAgvNGVcebmmX go-libp2p-blankhost
[done] [install] 1ms   QmaPbCnUMBohSGo3KnxEa2bHqyJVVeEEcwtqJAYxerieBo go-libp2p-crypto
[done] [install] 0s    QmNWCEvi7bPRcvqAV8AKLGVNoQdArWi7NJayka2SM4XtRe go-smux-yamux
[done] [install] 1ms   QmQvJiADDe7JR4m968MwXobTCCzUqQkP87aRHe29MEBGHV go-logging
[done] [install] 0s    QmVniQJkdzLZaZwzwMdd3dJTvWiJ1DQEkreVy6hs6h7Vk5 go-smux-multistream
[done] [install] 3ms   QmXYjuNuxVzXKJCfWasQk1RqkhVLDM9jtUKhqc2WPQmFSB go-libp2p-peer
[done] [install] 1ms   Qmf7GSJ4omRJsvA9uzTqzbnVhq4RWLPzjzW4xJzUta4dKE go-libp2p-circuit
[done] [install] 1ms   QmS7xUmsTdVNU2t1bPV6o9aXuXfufAjNGYgh2bcN2z9DAs go-multiaddr-dns
[done] [install] 0s    QmYkCrTwivapqdB3JbwvwvxymseahVkcm46ThRMAA24zCr go-libp2p-interface-connmgr
[done] [install] 1ms   QmWchsfMt9Re1CQaiHqPQC1DrZ9bkpa6n229dRYkGyLXNh dns
[done] [install] 1ms   QmTEmsyNnckEq8rEfALfdhLHjrEHGoSGFDrAYReuetn7MC go-net
[done] [install] 0s    QmYNGtJHgaGZkpzq8yG6Wxqm6EQTKqgpBfnyyGBKbZeDUi go-randbuf
[done] [install] 0s    QmQPWTeQJnJE7MYu6dJTiNTQRNuqBr41dis6UgY6Uekmgd keccakpg
[done] [install] 1ms   QmfJHywXQu98UeZtGJBQrPAR6AtmDjjbe3qjTo9piXHPnx murmur3
[done] [install] 1ms   QmY9JXR3FupnYAYJWK9aMr9bCpqWKcToQ1tz8DVGTrHpHw go-stream-muxer
[done] [install] 1ms   QmcyaFHbyiZfoX5GTpcqqCPYmbjYNAhRDekXSJPFHdYNSV go.uuid
[done] [install] 3ms   QmS4L8WB9RLZLu9YbS19cHJVjQnuvTyGaGKs75DtmX4Jyo go-reuseport
[done] [install] 1ms   QmdicniYXy49AFCSVTZeYmo997kT5XJRzZLokzJCrywR2U go-ws-transport
[done] [install] 1ms   QmNp85zy9RLrQ5oQD4hPyS39ezrrXpcaa7R4Y9kxdWQLLQ go-cid
[done] [install] 1ms   QmQq9YzmdFdWNTDdArueGyD7L5yyiRQigrRHJnTGkxcEjT go-libp2p-interface-pnet
[done] [install] 1ms   QmQFhPsJCp82az4SXbziP9QcVSqggEELnV9wGZqMR1EfMB go-smux-spdystream
[done] [install] 1ms   QmQ8t8yZJv6bTgnDcHMPMgpUcSTnpNMGPjFxmGwZ2MWak9 go-nat
[done] [install] 1ms   QmQ51pHe6u7CWodkUGDLqaCEMchkbMt7VEZnECF5mp6tVb ed25519
[done] [install] 1ms   QmWq5PJgAQKDWQerAijYUVKW8mN5MDatK5j7VMp8rizKQd btcec
[done] [install] 1ms   QmVxf27kucSvCLiCq6dAXjDU2WG3xZN9ae7Ny6osroP28u yamux
[done] [install] 1ms   QmNhVCV7kgAqW6oh6n8m9myxT2ksGPhVZnHkzkBvR5qg2d go-multicodec-packed
[done] [install] 1ms   Qmaau1d1WjnQdTYfRYfFVsCS97cgD8ATyrKuNoEfexL7JZ go-text
[done] [install] 1ms   QmcLqWSFsaQ8Ujh8Ys8i9JPHVy1CcdPoqV23M9S3ufdVbn go-sockaddr
[done] [install] 3ms   Qma73Sqt13DzHzveZ667BBfraM7MuMrPepUXjmv812JhRS go-net-resolve-addr
[done] [install] 1ms   QmSGRM5Udmy1jsFBr1Cawez7Lt7LZ3ZKA23GGVEsiEW6F3 eventfd
[done] [install] 1ms   QmZH5VXfAJouGMyCCHTRPGCT3e5MG9Lu78Ln3YAYW1XTts websocket
[done] [install] 0s    QmafgXF3u3QSWErQoZ2URmQp5PFG384htoE7J338nS2H7T go-multibase
[done] [install] 1ms   QmWjNfGgm61ABELTxPDwvNDm18j1EmQiPt9zXkCSEYgMDm spdystream
[done] [install] 2ms   QmQtBcHtRy9BxjawZjWJBn8aSKbqraBnQiVsc3wt9w9TTn goupnp
[done] [install] 1ms   Qmf2fBLzCvFxs3vvZaoQyKSTv2rjApek4F1kzRxAfK6P4P gateway
[done] [install] 0s    QmYsYNh6saxUYHajdj49uiRzdxQgiFTtymrjf3d1f2Cer4 go-nat-pmp
[done] [install] 1ms   QmeFPvhFJGXGiXAc9zunNxZjCaWgYQpcsdwip2NWLcccyw GoEndian
[done] [install] 1ms   QmfVj3x4D6Jkq9SEoi5n2NmoUomLwoeiwnYz2KQa15wRw6 base32
go get . 8] 0s
go get ./ui
go get ./apptest
go get ./cmd/
go get ./cmd/bs/
github.com/holochain/holochain-proto/cmd/bs
gx/ipfs/QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ/go-crypto/blake2b.supportAVX2: relocation target runtime.support_avx2 not defined
Makefile:43: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by iwealth** [comment] 2018-09-12 07:32
I'm also getting this error in macos

**Comment by umutkarakocold** [comment] 2018-09-12 07:33
I'm also getting this error on macos

**Comment by finzend** [comment] 2018-09-19 16:02
Yep, me too on MacOS (High Sierra, Intel Core i5, golang 1.11)

github.com/holochain/holochain-proto/cmd/bs
gx/ipfs/QmaPHkZLbQQbvcyavn8q1GFHg6o6yeceyHFSJ3Pjf3p3TQ/go-crypto/blake2b.supportAVX2: relocation target runtime.support_avx2 not defined
make: *** [all] Error 2

**Comment by ashishchandr70** [comment] 2018-09-20 14:36
I think the Holo team is busy with their upcoming releases....this thread isn't getting much love right now.

**Comment by maackle** [comment] 2018-09-21 09:54
Could you check and post your `go version`? A 3rd party package might have gone out of date...

**Comment by hellowodl** [comment] 2018-09-21 23:29
Hmm, just attempted to install Holochain in the light of the hackaton tomorrow morning, also faced by this issue

My "go version" output is "go version go1.11 linux/amd64"

**Comment by mitra42** [comment] 2018-09-22 03:57
Me too ... doing a clean go install and holo on a Mac.

**Comment by finzend** [comment] 2018-09-22 06:22
my go version: go1.11 darwin/amd64

**Comment by maackle** [comment] 2018-09-22 09:03
It definitely looks like this is a problem specific to Go 1.11, and a third-party package that hasn't been upgraded to work with it. 1.11 was released less than a month ago and we just haven't noticed yet.

For building from source, the recommendation is to compile using Go 1.10.x or earlier, which is confirmed to work (1.8.3 is also confirmed to work). Or, just use the latest precompiled binaries from https://github.com/holochain/holochain-proto/releases, which were also built against a previous version of Go.

**Comment by mitra42** [comment] 2018-09-22 22:24
Wouldnt it be useful to leave this Open until either the problem is fixed, or the documentation is fixed to reflect the need to install Go1.10 - https://developer.holochain.org/Install_Holochain tells you to get Go > 1.8 with the natural assumption being to use the latest stable version. 

Also ... the documentation doesn't say anything about getting precompiled releases.

**Comment by maackle** [comment] 2018-09-23 04:02
Good point @mitra42, I agree that the next step is ours to take. Reopening.

**Comment by ashishchandr70** [comment] 2018-09-24 17:52
> Could you check and post your `go version`? A 3rd party package might have gone out of date...

go version go1.11 windows/386

**Comment by Connoropolous** [comment] 2018-10-04 23:58
Apologies to those who've encountered this! I work on the documentation and didn't see this till now. I will update the Installation documentation now to mention to use version 1.10

**Comment by Connoropolous** [comment] 2018-10-05 00:09
I've updated the installation instructions now:
https://developer.holochain.org/Install_Holochain

**Comment by Connoropolous** [comment] 2018-10-05 12:55
@mitra42 I will close the issue now, but also I will add some documentation about installing using the precompiled releases

cc @ddd-mtl

**Closed as completed by Connoropolous** 2018-10-05 12:55 UTC
