### ISSUE TITLE
GET is broken since fix to #595

### ISSUE THREAD

**Issue by artbrock** [Holochain/holochain-proto#604] opened 2018-03-10 09:25 UTC
DHT reads are no longer working and we need them working for Hackathon. CRITICAL!

**Comment by zippy** [comment] 2018-03-10 20:14
Can't reproduce.  Updated fractal-wiki clutter and cointoss to all work with latest hcdev (core v 21).  Also update `bin/test.examples` script to be able to pull from develop branch to see how things are working, and they all seem to work.

**Comment by jeznag** [comment] 2018-03-11 02:36
@zippy failing tests for getLinks here: https://github.com/jeznag/HoloWorld/blob/get-links-not-working/test/holoWorld.json

**Comment by zippy** [comment] 2018-03-11 05:10
Here are the two bugs in the code that need fixing to make the tests pass:

Change the `doGetLinkLoad` function to:
``` javascript
function doGetLinkLoad(base, tag) {
  // get the tag from the base in the DHT
    var links = getLinks(base, tag,{Load:true});
  var linksFilled = [];
  for (var i = 0; i < links.length; i++) {
    var link = links[i].Entry;
    linksFilled.push(link);
  }
  return linksFilled;
}
```

and then change the call to that same function from inside `holoWorldEntryGetAll` to:
``` javascript
var entries = doGetLinkLoad(worldHash, 'world');
```
because you need to use the same tag name you used when adding the link.

Then all the tests pass.

**Comment by jeznag** [comment] 2018-03-11 21:14
Ah thanks @zippy! I'll write up some documentation on this as it wasn't clear how to use getLinks/anchors.

**Comment by philipbeadle** [comment] 2018-03-13 06:02
Looks like we can close this one.

**Closed by philipbeadle** 2018-03-13 06:02 UTC
Labels: bug, in progress
